# Generated by Django 3.2.6 on 2021-11-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Update',
            new_name='updated',
        ),
    ]
